[package]
name = "windlang-rust"
version = "0.1.0"
edition = "2021"
default-run = "cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# strip = true
debug = true

[dependencies]
enum-as-inner = "0.5.0"
paste = "1.0"
